# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TabView.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(721, 695)
        self.Tab = QtWidgets.QTabWidget(Dialog)
        self.Tab.setGeometry(QtCore.QRect(10, 10, 691, 631))
        self.Tab.setObjectName("Tab")
        self.Insertion = QtWidgets.QWidget()
        self.Insertion.setObjectName("Insertion")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Insertion)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_pilote = QtWidgets.QLineEdit(self.Insertion)
        self.lineEdit_pilote.setObjectName("lineEdit_pilote")
        self.verticalLayout.addWidget(self.lineEdit_pilote)
        self.lineEdit_avion = QtWidgets.QLineEdit(self.Insertion)
        self.lineEdit_avion.setObjectName("lineEdit_avion")
        self.verticalLayout.addWidget(self.lineEdit_avion)
        self.comboBox_pilote = QtWidgets.QComboBox(self.Insertion)
        self.comboBox_pilote.setObjectName("comboBox_pilote")
        self.verticalLayout.addWidget(self.comboBox_pilote)
        self.comboBox_pilote2 = QtWidgets.QComboBox(self.Insertion)
        self.comboBox_pilote2.setObjectName("comboBox_pilote2")
        self.verticalLayout.addWidget(self.comboBox_pilote2)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.Insertion)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.verticalLayout.addWidget(self.dateTimeEdit)
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.Insertion)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.verticalLayout.addWidget(self.dateTimeEdit_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.tableView = QtWidgets.QTableView(self.Insertion)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_3.addWidget(self.tableView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.afficher = QtWidgets.QPushButton(self.Insertion)
        self.afficher.setObjectName("afficher")
        self.horizontalLayout.addWidget(self.afficher)
        self.Effacer = QtWidgets.QPushButton(self.Insertion)
        self.Effacer.setObjectName("Effacer")
        self.horizontalLayout.addWidget(self.Effacer)
        self.calculer = QtWidgets.QPushButton(self.Insertion)
        self.calculer.setObjectName("calculer")
        self.horizontalLayout.addWidget(self.calculer)
        self.pushButton_4 = QtWidgets.QPushButton(self.Insertion)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.Tab.addTab(self.Insertion, "")
        self.Limites = QtWidgets.QWidget()
        self.Limites.setObjectName("Limites")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Limites)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.Limites)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.lineEdit = QtWidgets.QLineEdit(self.Limites)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.groupBox = QtWidgets.QGroupBox(self.Limites)
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 30, 113, 29))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(160, 30, 113, 29))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_4.addWidget(self.groupBox)
        self.Tab.addTab(self.Limites, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.Tab.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.Tab.addTab(self.tab_6, "")

        self.retranslateUi(Dialog)
        self.Tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.afficher.setText(_translate("Dialog", "Afficher"))
        self.Effacer.setText(_translate("Dialog", "Effacer"))
        self.calculer.setText(_translate("Dialog", "Calculer"))
        self.pushButton_4.setText(_translate("Dialog", "PushButton"))
        self.Tab.setTabText(self.Tab.indexOf(self.Insertion), _translate("Dialog", "Insertion"))
        self.groupBox.setTitle(_translate("Dialog", "GroupBox"))
        self.Tab.setTabText(self.Tab.indexOf(self.Limites), _translate("Dialog", "Limites"))
        self.Tab.setTabText(self.Tab.indexOf(self.tab_5), _translate("Dialog", "Page"))
        self.Tab.setTabText(self.Tab.indexOf(self.tab_6), _translate("Dialog", "Page"))
